# Generated by Django 4.0.2 on 2022-07-07 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custimage', models.ImageField(upload_to='img')),
                ('Aadharimage', models.ImageField(upload_to='img')),
                ('VoterIDimage', models.ImageField(upload_to='img')),
                ('Doc1image', models.ImageField(upload_to='img')),
                ('Doc2image', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_Name', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '5. branch',
            },
        ),
        migrations.CreateModel(
            name='calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(choices=[('FLAT', 'FLAT '), ('REDUCING', 'REDUCING')], max_length=100)),
                ('loanMode', models.CharField(choices=[('WEEKLY', 'WEEKLY '), ('BIWEEKLY', 'BIWEEKLY'), ('MONTHLY', 'MONTHLY')], max_length=100)),
                ('rateOfIntrest', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('terms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '2. circle',
            },
        ),
        migrations.CreateModel(
            name='CoInsurerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoInsurerRelation', models.CharField(max_length=50, null=True)),
                ('CoInsurerName', models.IntegerField()),
                ('CoOccupation', models.CharField(max_length=50, null=True)),
                ('CoInsurerDOB', models.DateField(null=True)),
                ('CoInsurerAge', models.IntegerField()),
                ('KYCIDType', models.CharField(max_length=50, null=True)),
                ('KYCID', models.CharField(max_length=50, null=True)),
                ('RemarkComments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='commonfield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationId', models.CharField(max_length=50, null=True)),
                ('Branch', models.CharField(max_length=50, null=True)),
                ('CenterId', models.CharField(max_length=50, null=True)),
                ('CustomerId', models.CharField(max_length=50, null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('Cycle', models.CharField(max_length=50, null=True)),
                ('Group', models.CharField(choices=[('kailash', 'kailash')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditBureauDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OtherMFISHG', models.CharField(max_length=50, null=True)),
                ('InternalRating', models.FloatField()),
                ('OtherLoanAmount', models.IntegerField()),
                ('OtherOSAmount', models.CharField(max_length=50, null=True)),
                ('EligibleMontlyEMI', models.FloatField()),
                ('CBResponseDate', models.DateField(null=True)),
                ('GenericMFIScore', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='customerKYC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Aadhaar', models.IntegerField()),
                ('VoterCard', models.CharField(max_length=50, null=True)),
                ('OtherKYCIdtype', models.CharField(max_length=50, null=True)),
                ('OtherKYCId', models.CharField(max_length=50, null=True)),
                ('FirstName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(max_length=50, null=True)),
                ('DateOfBirth', models.DateField(null=True)),
                ('Age', models.IntegerField()),
                ('MaritalStatus', models.CharField(max_length=50, null=True)),
                ('FSName', models.CharField(max_length=50, null=True)),
                ('FSType', models.CharField(max_length=50, null=True)),
                ('FSDateOfBirth', models.DateField(null=True)),
                ('MothersName', models.CharField(max_length=50, null=True)),
                ('FSAdhaar', models.IntegerField()),
                ('Caste', models.CharField(max_length=50, null=True)),
                ('Religion', models.CharField(max_length=50, null=True)),
                ('Qualification', models.CharField(max_length=50, null=True)),
                ('Occupation', models.CharField(max_length=50, null=True)),
                ('AddressLine1', models.TextField()),
                ('AddressLine2', models.TextField()),
                ('AddressLine3', models.TextField()),
                ('PreferredLanguage', models.CharField(max_length=50, null=True)),
                ('Village', models.CharField(max_length=100, null=True)),
                ('District', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=50, null=True)),
                ('Pincode', models.IntegerField()),
                ('PhoneNumber', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerRegistered', models.DateField(null=True)),
                ('ApplicationApplied', models.DateField(null=True)),
                ('ExpectedDisbursementDate', models.DateField(null=True)),
                ('TopUp', models.BooleanField()),
                ('HouseVisit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientMonthlyEMIAmountCB', models.IntegerField()),
                ('MonthlyFamilyIncome', models.IntegerField()),
                ('MonthlyFamilyExpense', models.IntegerField()),
                ('ClientMonthlyEMIAmount', models.IntegerField()),
                ('FamilyMonthlyEMIAmount', models.IntegerField()),
                ('HouseType', models.CharField(max_length=50, null=True)),
                ('LandInAcre', models.FloatField()),
                ('NumberofAnimals', models.IntegerField()),
                ('PovertyLine', models.CharField(max_length=50, null=True)),
                ('BankName', models.CharField(max_length=50, null=True)),
                ('BankAccountNo', models.IntegerField()),
                ('ConfirmBankAccountNo', models.IntegerField()),
                ('BankIFSCCode', models.CharField(max_length=50, null=True)),
                ('ConfirmBankIFSCCode', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='haed_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haed_office_name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1. haed_office',
            },
        ),
        migrations.CreateModel(
            name='HouseholdDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyFamilyExpense', models.IntegerField()),
                ('MonthlyFamilyIncome', models.IntegerField()),
                ('ClientMonthlyEMIAmountCB', models.IntegerField()),
                ('CoClientMonthlyEMIAmountCB', models.IntegerField()),
                ('TotalFamilyMonthlyEMIAmount', models.IntegerField()),
                ('NumberofAnimals', models.IntegerField()),
                ('LandInAcre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InsuranceId', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanName', models.CharField(max_length=50, null=True)),
                ('Product', models.CharField(max_length=50, null=True)),
                ('loanMode', models.CharField(choices=[('WEEKLY', 'WEEKLY '), ('BIWEEKLY', 'BIWEEKLY'), ('MONTHLY', 'MONTHLY')], max_length=50, null=True)),
                ('LoanAmount', models.IntegerField()),
                ('InterestRate', models.FloatField()),
                ('RepayFrequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NomineeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomineeRelation', models.CharField(max_length=50, null=True)),
                ('NomineeName', models.CharField(max_length=50, null=True)),
                ('DateOfBirth', models.DateField(null=True)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryType', models.CharField(max_length=50, null=True)),
                ('ProductCategory', models.CharField(max_length=50, null=True)),
                ('Product', models.CharField(max_length=50, null=True)),
                ('LoanAmount', models.IntegerField()),
                ('AppliedAmount', models.IntegerField()),
                ('InterestRate', models.FloatField()),
                ('RepayFrequency', models.FloatField()),
                ('ProductInvoiceNumber', models.FloatField()),
                ('SanctionStatus', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurposeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purpose', models.CharField(max_length=50, null=True)),
                ('SubPurpose', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectionReasonComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RejectionReason', models.TextField()),
                ('Comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SharedServiceDetials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SharedServiceDetail', models.CharField(max_length=50, null=True)),
                ('SharedServiceRejectionCount', models.CharField(max_length=50, null=True)),
                ('BankValidationRemarks', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('circle_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.circle')),
                ('haed_office_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.haed_office')),
            ],
            options={
                'verbose_name_plural': '3. Zone',
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('circle_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.circle')),
                ('haed_office_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.haed_office')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.zone')),
            ],
            options={
                'verbose_name_plural': '4. region',
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='haed_office_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.haed_office'),
        ),
        migrations.CreateModel(
            name='centerId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerId', models.CharField(max_length=50, null=True)),
                ('agents_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branchName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.branch')),
            ],
        ),
        migrations.CreateModel(
            name='center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('branch_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.branch')),
                ('circle_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.circle')),
                ('haed_office_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.haed_office')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOAN.region')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOAN.zone')),
            ],
            options={
                'verbose_name_plural': '6. center',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='circle_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.circle'),
        ),
        migrations.AddField(
            model_name='branch',
            name='haed_office_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOAN.haed_office'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOAN.region'),
        ),
        migrations.AddField(
            model_name='branch',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOAN.zone'),
        ),
    ]
