# Generated by Django 4.0.2 on 2022-07-07 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LOAN', '0002_agent_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agents_Name', models.CharField(max_length=50, null=True)),
                ('branch_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.branch')),
                ('user_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
