# Generated by Django 4.0.2 on 2022-07-08 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LOAN', '0003_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center_ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerId', models.CharField(max_length=50, null=True)),
                ('agents_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branchName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOAN.branch')),
            ],
        ),
    ]
