# Generated by Django 4.0.2 on 2022-07-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0004_center_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centerid',
            name='agents_Name',
        ),
        migrations.RemoveField(
            model_name='centerid',
            name='branchName',
        ),
        migrations.DeleteModel(
            name='agent_data',
        ),
        migrations.DeleteModel(
            name='centerId',
        ),
    ]
