# Generated by Django 4.0.2 on 2022-07-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0005_remove_centerid_agents_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllImage',
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='Aadharimage',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='Custimage',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='Doc1image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='Doc2image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='VoterIDimage',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
