# Generated by Django 4.0.2 on 2022-07-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0007_alter_customerkyc_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Aadhaar',
            field=models.IntegerField(),
        ),
    ]
