# Generated by Django 4.0.2 on 2022-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0008_alter_customerkyc_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Aadhaar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
