# Generated by Django 4.0.2 on 2022-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0009_alter_customerkyc_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdetails',
            name='BankAccountNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialdetails',
            name='ConfirmBankAccountNo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
