# Generated by Django 4.0.2 on 2022-07-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0010_alter_financialdetails_bankaccountno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerkyc',
            name='Application_No',
            field=models.IntegerField(null=True),
        ),
    ]
