# Generated by Django 4.0.2 on 2022-07-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0011_customerkyc_application_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerkyc',
            name='AppliedAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='BankAccountNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='BankIFSCCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='BankName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='Branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='CategoryType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='CenterId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='ClientMonthlyEMIAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='ClientMonthlyEMIAmountCB',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='CoInsurerAge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='CoInsurerDOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='CoInsurerName',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='CoInsurerRelation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='CoOccupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='ConfirmBankAccountNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='ConfirmBankIFSCCode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='FamilyMonthlyEMIAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='HouseType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='InterestRate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='KYCID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='KYCIDType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='LandInAcre',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='LoanAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='MonthlyFamilyExpense',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='MonthlyFamilyIncome',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='NomineeName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='NomineeRelation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='NumberofAnimals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='PovertyLine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='Product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='RemarkComments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='RepayFrequency',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
