# Generated by Django 4.0.2 on 2022-07-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0012_customerkyc_appliedamount_customerkyc_bankaccountno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerkyc',
            name='NomineeAge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerkyc',
            name='NomineeDateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
