# Generated by Django 4.0.2 on 2022-07-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0013_customerkyc_nomineeage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerkyc',
            name='ProductCategory',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
