# Generated by Django 4.0.2 on 2022-07-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0014_customerkyc_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerkyc',
            name='PurposeId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
