# Generated by Django 4.0.2 on 2022-07-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0015_customerkyc_purposeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='CoInsurerName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
