# Generated by Django 4.0.2 on 2022-07-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0016_alter_customerkyc_coinsurername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerkyc',
            name='AppliedAmount',
        ),
    ]
