# Generated by Django 4.0.2 on 2022-07-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0017_remove_customerkyc_appliedamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerkyc',
            name='ClientMonthlyEMIAmount',
        ),
        migrations.RemoveField(
            model_name='customerkyc',
            name='ClientMonthlyEMIAmountCB',
        ),
        migrations.RemoveField(
            model_name='customerkyc',
            name='FamilyMonthlyEMIAmount',
        ),
        migrations.RemoveField(
            model_name='customerkyc',
            name='MonthlyFamilyExpense',
        ),
        migrations.RemoveField(
            model_name='customerkyc',
            name='MonthlyFamilyIncome',
        ),
    ]
