# Generated by Django 4.0.2 on 2022-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0018_remove_customerkyc_clientmonthlyemiamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Aadhaar',
            field=models.BigIntegerField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='Application_No',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='VoterCard',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
