# Generated by Django 4.0.2 on 2022-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0019_alter_customerkyc_aadhaar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Aadhaar',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='BankAccountNo',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='ConfirmBankAccountNo',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='FSAdhaar',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='PhoneNumber',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
