# Generated by Django 4.0.2 on 2022-07-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0020_alter_customerkyc_aadhaar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Application_No',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
