# Generated by Django 4.0.2 on 2022-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0021_alter_customerkyc_application_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Aadhaar',
            field=models.BigIntegerField(error_messages={'msg': 'Please Enter Your Aadhar Card Number'}, unique=True),
        ),
    ]
