# Generated by Django 4.0.2 on 2022-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0022_alter_customerkyc_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Aadhaar',
            field=models.BigIntegerField(error_messages={'required': 'Please Enter Your Aadhar Card Number'}, unique=True),
        ),
    ]
