# Generated by Django 4.0.2 on 2022-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0023_alter_customerkyc_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='OtherKYCId',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='OtherKYCIdtype',
            field=models.CharField(choices=[('Ration card', 'Ration card'), ('Pen card', 'Pen card'), ('Driving license', 'Driving license')], max_length=50, null=True),
        ),
    ]
