# Generated by Django 4.0.2 on 2022-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0024_alter_customerkyc_otherkycid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='OtherKYCId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
