# Generated by Django 4.0.2 on 2022-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0025_alter_customerkyc_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Caste',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('Scheduled Tribes', 'Scheduled Tribes'), ('Schedules Castes', 'Schedules Castes'), ('Minority', 'Minority')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='FSType',
            field=models.CharField(choices=[('Father', 'Father'), ('Spouse', 'Spouse')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='MaritalStatus',
            field=models.CharField(choices=[('Married', 'Married'), ('UnMarried', 'UnMarried'), ('Widow', 'Widow'), ('Separated', 'Separated'), ('Widower', 'Widower'), ('Divorced', 'Divorced')], max_length=50, null=True),
        ),
    ]
