# Generated by Django 4.0.2 on 2022-07-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0026_alter_customerkyc_caste_alter_customerkyc_fstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Qualification',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Metric', 'Metric'), ('Intermediate', 'Intermediate'), ('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='Religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
