# Generated by Django 4.0.2 on 2022-07-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0029_customerkyc_confirmaddressline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='PurposeId',
            field=models.CharField(choices=[('Transportation', 'Transportation'), ('Agriculture', 'Agriculture'), ('Tranding', 'Tranding'), ('Production', 'Production')], max_length=50, null=True),
        ),
    ]
