# Generated by Django 4.0.2 on 2022-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0030_alter_customerkyc_purposeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='CategoryType',
            field=models.CharField(choices=[('SNT', 'SNT'), ('IGL', 'IGL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerkyc',
            name='RemarkComments',
            field=models.CharField(max_length=500),
        ),
    ]
