# Generated by Django 4.0.2 on 2022-07-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0031_alter_customerkyc_categorytype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerkyc',
            old_name='Branch',
            new_name='BranchName',
        ),
    ]
