# Generated by Django 4.0.2 on 2022-07-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0032_rename_branch_customerkyc_branchname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='confirmPincode',
            field=models.IntegerField(null=True),
        ),
    ]
