# Generated by Django 4.0.2 on 2022-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0033_alter_customerkyc_confirmpincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='PreferredLanguage',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], max_length=50, null=True),
        ),
    ]
