# Generated by Django 4.0.2 on 2022-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0034_alter_customerkyc_preferredlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='KYCIDType',
            field=models.CharField(choices=[('Aadhar card', 'Aadhar card'), ('Ration card', 'Ration card'), ('Pen card', 'Pen card'), ('Driving license', 'Driving license')], max_length=50, null=True),
        ),
    ]
