# Generated by Django 4.0.2 on 2022-07-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0036_alter_customerkyc_kycidtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerkyc',
            name='GroupName',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50, null=True),
        ),
    ]
