# Generated by Django 4.0.2 on 2022-07-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0037_customerkyc_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='BankName',
            field=models.CharField(choices=[('Bank of Baroda', 'Bank of Baroda'), ('Bank of India', 'Bank of India'), ('Bank of Maharashtra', 'Bank of Maharashtra'), ('Canara Bank', 'Canara Bank'), ('Central Bank of India', 'Central Bank of India'), ('Indian Bank', 'Indian Bank'), ('Indian Overseas Bank', 'Indian Overseas Bank'), ('Punjab & Sind Bank', 'Punjab & Sind Bank'), ('Punjab National Bank', 'Punjab National Bank'), ('State Bank of India', 'State Bank of India'), ('UCO Bank', 'UCO Bank'), ('Union Bank of India', 'Union Bank of India'), ('Axis Bank', 'Axis Bank'), ('Bandhan Bank', 'Bandhan Bank'), ('CSB Bank', 'CSB Bank'), ('City Union Bank', 'City Union Bank'), ('DCB Bank', 'DCB Bank'), ('Dhanlaxmi Bank', 'Dhanlaxmi Bank'), ('Federal Bank', 'Federal Bank'), ('HDFC Bank', 'HDFC Bank'), ('ICICI Bank', 'ICICI Bank'), ('Induslnd Bank', 'Induslnd Bank'), ('IDFC First Bank', 'IDFC First Bank'), ('Jammu & Kashmir Bank', 'Jammu & Kashmir Bank'), ('Karnataka Bank', 'Karnataka Bank'), ('Karur Vysya Bank', 'Karur Vysya Bank'), ('Kotak Mahindra Bank', 'Kotak Mahindra Bank'), ('Lakshmi Vilas Bank', 'Lakshmi Vilas Bank'), ('Nainital Bank', 'Nainital Bank'), ('RBL Bank', 'RBL Bank'), ('South Indian Bank', 'South Indian Bank'), ('Tamilnad Mercantile Bank', 'Tamilnad Mercantile Bank'), ('YES Bank', 'YES Bank'), ('IDBI Bank', 'IDBI Bank')], max_length=50, null=True),
        ),
    ]
