# Generated by Django 4.0.2 on 2022-07-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0038_alter_customerkyc_bankname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Aadhaar',
            field=models.BigIntegerField(unique=True),
        ),
    ]
