# Generated by Django 4.0.2 on 2022-08-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0040_alter_customerkyc_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Aadhaar',
            field=models.BigIntegerField(unique=True),
        ),
    ]
