# Generated by Django 4.0.2 on 2022-08-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOAN', '0041_alter_customerkyc_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkyc',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('4', 'Othersssss')], max_length=50, null=True),
        ),
    ]
